-- ============================================================================
-- Bencris · Catch-up for the hosted Supabase project
-- ----------------------------------------------------------------------------
-- Paste this whole file into the SQL Editor of the hosted project and run it.
--
-- It applies the 8 migrations the hosted database is missing. Everything up
-- to and including the payment-proof migration is already there and is NOT
-- repeated, because re-running it would fail on objects that already exist.
--
-- It runs inside a single transaction: if anything fails, nothing is applied
-- and the project is left exactly as it was. The 9 dishes already in the
-- project are kept; every data insert below uses ON CONFLICT DO NOTHING.
--
-- Generated by scripts/build-hosted-catchup.mjs
-- ============================================================================

begin;


-- ============================================================================
-- 20260805000000_promotions.sql
-- ============================================================================
-- ============================================================================
-- Bencris · Promotional codes
-- ----------------------------------------------------------------------------
-- A karinderya's cheapest marketing lever: "SULIT10 for 10% off merienda".
-- Free to run, no ad spend, and it gives the owner a measurable reason for a
-- diner to come back.
--
-- SECURITY — the discount is computed HERE, never accepted from the client.
-- This is the same rule that already governs prices in create_ticket(): the
-- app sends a code string, and Postgres decides what (if anything) it is worth.
-- A tampered client that posts {"discount": 5000} changes nothing, because no
-- caller has an INSERT grant on orders and create_ticket ignores the field.
--
-- Redemption is counted inside the same transaction that inserts the order, so
-- a limited-run promo cannot be over-redeemed by two diners checking out at the
-- same moment (the UPDATE ... WHERE used_count < usage_limit takes the row lock).
-- ============================================================================

create table public.promo_codes (
  code         text primary key,
  label        text not null default '',
  -- 'percent' → value is 0-100. 'fixed' → value is pesos off the subtotal.
  kind         text not null check (kind in ('percent', 'fixed')),
  value        numeric(10,2) not null check (value > 0),
  -- Guards the owner's margin: a promo can require a minimum spend, and a
  -- percentage promo can be capped in pesos.
  min_subtotal numeric(10,2) not null default 0 check (min_subtotal >= 0),
  max_discount numeric(10,2) check (max_discount is null or max_discount > 0),
  starts_at    timestamptz not null default now(),
  ends_at      timestamptz,
  -- NULL = unlimited redemptions.
  usage_limit  int check (usage_limit is null or usage_limit > 0),
  used_count   int not null default 0 check (used_count >= 0),
  active       boolean not null default true,
  created_at   timestamptz not null default now(),

  constraint promo_percent_range
    check (kind <> 'percent' or value <= 100)
);

alter table public.promo_codes enable row level security;

-- Diners may READ active promos — these are advertised on the storefront and on
-- the tarpaulin outside, so the code is not a secret. What the code is *worth*
-- is still decided server-side, which is the part that matters.
create policy "promo_codes_read_active"
  on public.promo_codes for select
  using (active or public.is_staff());

create policy "promo_codes_admin_write"
  on public.promo_codes for all
  using (public.is_admin()) with check (public.is_admin());

grant select on public.promo_codes to anon, authenticated;
grant insert, update, delete on public.promo_codes to authenticated;

comment on table public.promo_codes is
  'Owner-defined discounts. Only create_ticket() may redeem one; the value is never taken from the client.';

-- ---------------------------------------------------------------------------
-- orders — keep the arithmetic auditable.
--
-- `total` stays what the diner actually owes, so every existing reader (the
-- cashier screen, the receipt, the analytics dashboard) keeps working untouched.
-- subtotal and discount are added alongside it so a settled sale can always be
-- explained: subtotal - discount = total.
-- ---------------------------------------------------------------------------
alter table public.orders
  add column subtotal   numeric(10,2) not null default 0 check (subtotal >= 0),
  add column discount   numeric(10,2) not null default 0 check (discount >= 0),
  add column promo_code text references public.promo_codes (code) on delete set null;

-- Backfill: every historical order predates promos, so it was sold at list price.
update public.orders set subtotal = total where subtotal = 0;

comment on column public.orders.subtotal is 'Menu price of the items before any discount.';
comment on column public.orders.discount is 'Pesos taken off by promo_code. subtotal - discount = total.';

-- ---------------------------------------------------------------------------
-- promo_discount_for() — the single definition of what a code is worth.
--
-- Deliberately a pure function of (code, subtotal): create_ticket() calls it to
-- charge, and preview_promo() calls it to display. One implementation means the
-- cart can never quote a discount the checkout then refuses to honour.
--
-- Returns 0 for anything invalid rather than raising, so a mistyped code is a
-- quiet "that didn't work" in the UI and not a failed checkout.
-- ---------------------------------------------------------------------------
create or replace function public.promo_discount_for(
  p_code     text,
  p_subtotal numeric
)
returns numeric
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_promo    public.promo_codes;
  v_discount numeric(10,2);
begin
  if p_code is null or trim(p_code) = '' then
    return 0;
  end if;

  select * into v_promo
    from public.promo_codes
   where code = upper(trim(p_code));

  if v_promo.code is null
     or not v_promo.active
     or v_promo.starts_at > now()
     or (v_promo.ends_at is not null and v_promo.ends_at < now())
     or (v_promo.usage_limit is not null and v_promo.used_count >= v_promo.usage_limit)
     or p_subtotal < v_promo.min_subtotal
  then
    return 0;
  end if;

  v_discount := case v_promo.kind
                  when 'percent' then p_subtotal * v_promo.value / 100
                  else v_promo.value
                end;

  if v_promo.max_discount is not null then
    v_discount := least(v_discount, v_promo.max_discount);
  end if;

  -- Never hand out more than the order is worth: a ₱50-off code on a ₱35 order
  -- discounts ₱35, not ₱50. Without this the total could go negative.
  return round(least(v_discount, p_subtotal), 2);
end;
$$;

grant execute on function public.promo_discount_for(text, numeric) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- preview_promo() — what the cart screen calls as the diner types a code.
--
-- Returns the reason on failure so the UI can say "spend ₱50 more" instead of
-- a flat "invalid", which is the difference between an abandoned cart and a
-- bigger one.
-- ---------------------------------------------------------------------------
create or replace function public.preview_promo(
  p_code     text,
  p_subtotal numeric default 0
)
returns table (valid boolean, discount numeric, label text, reason text)
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_promo    public.promo_codes;
  v_discount numeric(10,2);
begin
  select * into v_promo from public.promo_codes where code = upper(trim(coalesce(p_code, '')));

  if v_promo.code is null then
    return query select false, 0::numeric, ''::text, 'That code does not exist.'::text;
    return;
  end if;

  if not v_promo.active
     or v_promo.starts_at > now()
     or (v_promo.ends_at is not null and v_promo.ends_at < now())
  then
    return query select false, 0::numeric, v_promo.label, 'That promo is not running right now.'::text;
    return;
  end if;

  if v_promo.usage_limit is not null and v_promo.used_count >= v_promo.usage_limit then
    return query select false, 0::numeric, v_promo.label, 'That promo has been fully claimed.'::text;
    return;
  end if;

  if p_subtotal < v_promo.min_subtotal then
    return query select false, 0::numeric, v_promo.label,
      format('Spend at least %s to use this.', to_char(v_promo.min_subtotal, 'FM999999.00'))::text;
    return;
  end if;

  v_discount := public.promo_discount_for(v_promo.code, p_subtotal);
  return query select true, v_discount, v_promo.label, ''::text;
end;
$$;

grant execute on function public.preview_promo(text, numeric) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- create_ticket() — now prices, discounts, and redeems in one transaction.
--
-- The redemption UPDATE carries its own `used_count < usage_limit` guard. Two
-- diners racing for the last redemption of a 50-use promo therefore serialise
-- on the row lock, and the loser is charged full price rather than both being
-- let through.
-- ---------------------------------------------------------------------------
create or replace function public.create_ticket(
  p_items          jsonb,
  p_customer_name  text default null,
  p_payment_method text default 'cash',
  p_promo_code     text default null
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_items    jsonb := '[]'::jsonb;
  v_subtotal numeric(10,2) := 0;
  v_discount numeric(10,2) := 0;
  v_code     text;
  v_promo    text := nullif(upper(trim(coalesce(p_promo_code, ''))), '');
  v_order    public.orders;
  v_row      record;
  v_method   text := lower(coalesce(p_payment_method, 'cash'));
  v_settings public.payment_settings;
  v_claimed  int;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'a ticket needs at least one item';
  end if;

  if v_method not in ('cash', 'gcash') then
    raise exception 'payment method must be cash or gcash';
  end if;

  select * into v_settings from public.payment_settings where id = 1;
  if v_method = 'gcash' and not coalesce(v_settings.gcash_enabled, true) then
    raise exception 'GCash is not being accepted right now';
  end if;
  if v_method = 'cash' and not coalesce(v_settings.cash_enabled, true) then
    raise exception 'cash is not being accepted right now';
  end if;

  -- Resolve every line against the live menu, collapsing duplicate ids.
  for v_row in
    select d.id,
           d.name,
           d.price,
           sum(greatest(1, coalesce((item ->> 'qty')::int, 1)))::int as qty
    from jsonb_array_elements(p_items) as item
    join public.dishes d on d.id = item ->> 'id'
    where d.available
    group by d.id, d.name, d.price
  loop
    v_items := v_items || jsonb_build_object(
      'id', v_row.id, 'name', v_row.name, 'qty', v_row.qty, 'price', v_row.price
    );
    v_subtotal := v_subtotal + (v_row.price * v_row.qty);
  end loop;

  if jsonb_array_length(v_items) = 0 then
    raise exception 'none of the requested dishes are available';
  end if;

  -- Claim the redemption first. If the guard fails the promo was exhausted
  -- between the diner's preview and this insert, so they simply pay list price.
  if v_promo is not null then
    v_discount := public.promo_discount_for(v_promo, v_subtotal);

    if v_discount > 0 then
      update public.promo_codes
         set used_count = used_count + 1
       where code = v_promo
         and (usage_limit is null or used_count < usage_limit);

      get diagnostics v_claimed = row_count;
      if v_claimed = 0 then
        v_discount := 0;
        v_promo    := null;
      end if;
    else
      v_promo := null;
    end if;
  end if;

  v_code := public.generate_ticket_code();

  insert into public.orders
    (reference, ticket_code, customer_name, items,
     subtotal, discount, promo_code, total,
     payment_method, status, payment_status)
  values
    (v_code, v_code, nullif(trim(coalesce(p_customer_name, '')), ''), v_items,
     v_subtotal, v_discount, v_promo, v_subtotal - v_discount,
     v_method, 'pending', 'unpaid')
  returning * into v_order;

  return v_order;
end;
$$;

grant execute on function public.create_ticket(jsonb, text, text, text) to anon, authenticated;

-- Same trap as the previous migration: adding a defaulted parameter creates a
-- SECOND overload instead of replacing the old one, and two candidates make the
-- RPC ambiguous over PostgREST. Retire the 3-argument version.
drop function if exists public.create_ticket(jsonb, text, text);

-- ---------------------------------------------------------------------------
-- Launch promos. Deliberately modest — this is a karinderya, not a mall sale.
-- ---------------------------------------------------------------------------
insert into public.promo_codes (code, label, kind, value, min_subtotal, max_discount, usage_limit)
values
  ('SULIT10',  '10% off, merienda promo',        'percent', 10, 100, 30,  null),
  ('BAGONG20', '20 pesos off your first order',        'fixed',   20, 120, null, 200),
  ('BALIKBAYAN','15 pesos off, salamat sa pagbalik', 'fixed',   15, 90,  null, null)
on conflict (code) do nothing;


-- ============================================================================
-- 20260806000000_reviews.sql
-- ============================================================================
-- ============================================================================
-- Bencris · Dish ratings
-- ----------------------------------------------------------------------------
-- Food is bought on trust, and a first-time diner currently has nothing to go
-- on. Ratings used to live in the diner's own browser, which meant nobody else
-- could ever see them, so they were social proof that proved nothing.
--
-- SECURITY — a rating is only accepted against a ticket that was actually
-- settled AND that actually contained the dish. That check runs here, not in
-- the browser, so ratings cannot be manufactured by anyone holding the
-- publishable key. It is the same principle as pricing: the client states an
-- intention, the database decides whether it is true.
--
-- Diners stay anonymous, so there is no account to hang a review off. The
-- ticket code is the proof of purchase, and one ticket may rate a given dish
-- exactly once.
-- ============================================================================

create table public.reviews (
  id          uuid primary key default gen_random_uuid(),
  dish_id     text not null references public.dishes (id) on delete cascade,
  ticket_code text not null,
  rating      int  not null check (rating between 1 and 5),
  comment     text not null default '',
  author_name text,
  created_at  timestamptz not null default now(),

  -- One rating per dish per ticket. Re-rating updates the existing row.
  constraint reviews_one_per_ticket_dish unique (ticket_code, dish_id)
);

create index reviews_dish_idx on public.reviews (dish_id);

alter table public.reviews enable row level security;

-- Anyone may read ratings: that is the entire point of publishing them.
create policy "reviews_read_all" on public.reviews
  for select using (true);

-- Owners can remove abusive content. Nobody else writes directly.
create policy "reviews_admin_delete" on public.reviews
  for delete using (public.is_admin());

grant select on public.reviews to anon, authenticated;
grant delete on public.reviews to authenticated;

comment on table public.reviews is
  'Dish ratings. Insertable only through leave_review(), which verifies the ticket was settled and contained the dish.';

-- ---------------------------------------------------------------------------
-- dish_ratings — the average and count the menu actually displays.
--
-- A view rather than columns on `dishes`: ratings change independently of the
-- menu, and a stored average would need a trigger to stay honest.
-- ---------------------------------------------------------------------------
create view public.dish_ratings as
  select dish_id,
         round(avg(rating)::numeric, 1) as average,
         count(*)::int                  as total
  from public.reviews
  group by dish_id;

grant select on public.dish_ratings to anon, authenticated;

-- ---------------------------------------------------------------------------
-- leave_review() — the only way a rating enters the system.
-- ---------------------------------------------------------------------------
create or replace function public.leave_review(
  p_ticket_code text,
  p_dish_id     text,
  p_rating      int,
  p_comment     text default '',
  p_author_name text default null
)
returns public.reviews
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code   text := upper(trim(coalesce(p_ticket_code, '')));
  v_order  public.orders;
  v_review public.reviews;
begin
  if p_rating is null or p_rating < 1 or p_rating > 5 then
    raise exception 'a rating must be between 1 and 5';
  end if;

  select * into v_order from public.orders where ticket_code = v_code;

  if v_order.id is null then
    raise exception 'no ticket %', p_ticket_code;
  end if;

  -- Only a settled ticket counts. An unpaid ticket is an intention, not a meal.
  if v_order.paid_at is null then
    raise exception 'ticket % has not been paid, so it cannot leave a rating', v_code;
  end if;

  -- Ratings are about a recent meal, not one from last year.
  if v_order.paid_at < now() - interval '30 days' then
    raise exception 'ticket % is older than 30 days', v_code;
  end if;

  -- The ticket must actually have contained the dish being rated.
  if not exists (
    select 1 from jsonb_array_elements(v_order.items) as item
    where item ->> 'id' = p_dish_id
  ) then
    raise exception 'ticket % did not include that dish', v_code;
  end if;

  insert into public.reviews (dish_id, ticket_code, rating, comment, author_name)
  values (
    p_dish_id,
    v_code,
    p_rating,
    left(trim(coalesce(p_comment, '')), 500),
    nullif(trim(coalesce(p_author_name, '')), '')
  )
  on conflict (ticket_code, dish_id) do update
    set rating     = excluded.rating,
        comment    = excluded.comment,
        created_at = now()
  returning * into v_review;

  return v_review;
end;
$$;

grant execute on function public.leave_review(text, text, int, text, text) to anon, authenticated;


-- ============================================================================
-- 20260807000000_customer_accounts.sql
-- ============================================================================
-- ============================================================================
-- Bencris · Optional customer accounts
-- ----------------------------------------------------------------------------
-- Ordering stays possible without an account. That is deliberate: on a meal
-- costing under a hundred pesos, a signup wall is the most reliable way to lose
-- the sale, and the ticket-code flow is what makes the counter fast.
--
-- What an account adds is everything that needs memory across visits:
--   * order history that survives clearing the browser
--   * payment history
--   * a live page showing whether the order is preparing, ready or completed
--   * loyalty stamps
--   * being told when a sold-out dish is back
--   * seeing new promotions the owner starts
--
-- A guest order simply has customer_id NULL and behaves exactly as before.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. orders gains an optional owner and an optional pickup time
-- ---------------------------------------------------------------------------
alter table public.orders
  add column customer_id uuid references auth.users (id) on delete set null,
  add column pickup_at   timestamptz;

create index orders_customer_idx on public.orders (customer_id)
  where customer_id is not null;

comment on column public.orders.customer_id is
  'NULL for a guest order. Set automatically when a signed-in customer checks out.';
comment on column public.orders.pickup_at is
  'When the diner said they would collect. NULL means as soon as it is ready.';

-- ---------------------------------------------------------------------------
-- 2. Reading orders
--
-- Guests keep the 24 hour window, which is what lets a ticket on a phone follow
-- itself with no account. A signed-in customer additionally sees their OWN
-- orders forever, which is the whole point of having an account.
-- ---------------------------------------------------------------------------
drop policy if exists "orders_select_recent_or_staff" on public.orders;

create policy "orders_select_own_recent_or_staff"
  on public.orders for select
  using (
    public.is_staff()
    or (customer_id is not null and customer_id = auth.uid())
    or created_at > now() - interval '24 hours'
  );

-- ---------------------------------------------------------------------------
-- 3. create_ticket() — records who ordered, if anyone, and when they will collect
-- ---------------------------------------------------------------------------
create or replace function public.create_ticket(
  p_items          jsonb,
  p_customer_name  text default null,
  p_payment_method text default 'cash',
  p_promo_code     text default null,
  p_pickup_at      timestamptz default null
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_items    jsonb := '[]'::jsonb;
  v_subtotal numeric(10,2) := 0;
  v_discount numeric(10,2) := 0;
  v_code     text;
  v_promo    text := nullif(upper(trim(coalesce(p_promo_code, ''))), '');
  v_order    public.orders;
  v_row      record;
  v_method   text := lower(coalesce(p_payment_method, 'cash'));
  v_settings public.payment_settings;
  v_claimed  int;
  v_customer uuid := auth.uid();
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'a ticket needs at least one item';
  end if;

  if v_method not in ('cash', 'gcash') then
    raise exception 'payment method must be cash or gcash';
  end if;

  -- Staff accounts are not customers. Without this a cashier testing the
  -- storefront would quietly attach their own orders to their staff account.
  if v_customer is not null and public.is_staff() then
    v_customer := null;
  end if;

  select * into v_settings from public.payment_settings where id = 1;
  if v_method = 'gcash' and not coalesce(v_settings.gcash_enabled, true) then
    raise exception 'GCash is not being accepted right now';
  end if;
  if v_method = 'cash' and not coalesce(v_settings.cash_enabled, true) then
    raise exception 'cash is not being accepted right now';
  end if;

  for v_row in
    select d.id,
           d.name,
           d.price,
           sum(greatest(1, coalesce((item ->> 'qty')::int, 1)))::int as qty
    from jsonb_array_elements(p_items) as item
    join public.dishes d on d.id = item ->> 'id'
    where d.available
    group by d.id, d.name, d.price
  loop
    v_items := v_items || jsonb_build_object(
      'id', v_row.id, 'name', v_row.name, 'qty', v_row.qty, 'price', v_row.price
    );
    v_subtotal := v_subtotal + (v_row.price * v_row.qty);
  end loop;

  if jsonb_array_length(v_items) = 0 then
    raise exception 'none of the requested dishes are available';
  end if;

  if v_promo is not null then
    v_discount := public.promo_discount_for(v_promo, v_subtotal);

    if v_discount > 0 then
      update public.promo_codes
         set used_count = used_count + 1
       where code = v_promo
         and (usage_limit is null or used_count < usage_limit);

      get diagnostics v_claimed = row_count;
      if v_claimed = 0 then
        v_discount := 0;
        v_promo    := null;
      end if;
    else
      v_promo := null;
    end if;
  end if;

  v_code := public.generate_ticket_code();

  insert into public.orders
    (reference, ticket_code, customer_name, customer_id, items,
     subtotal, discount, promo_code, total,
     payment_method, status, payment_status, pickup_at)
  values
    (v_code, v_code, nullif(trim(coalesce(p_customer_name, '')), ''), v_customer, v_items,
     v_subtotal, v_discount, v_promo, v_subtotal - v_discount,
     v_method, 'pending', 'unpaid', p_pickup_at)
  returning * into v_order;

  return v_order;
end;
$$;

grant execute on function public.create_ticket(jsonb, text, text, text, timestamptz) to anon, authenticated;

-- Retire the previous signature so PostgREST is never ambiguous.
drop function if exists public.create_ticket(jsonb, text, text, text);

-- Records when the diner actually walked away with the food. This is what the
-- loyalty count is based on, so it has to be a real timestamp rather than an
-- inference from the status.
alter table public.orders add column completed_at timestamptz;

-- ---------------------------------------------------------------------------
-- 4. advance_order_status() — the kitchen flow, usable by the counter too
--
-- The counter is the same person as the kitchen in a karinderya this size, so
-- restricting status changes to the owner made the feature unusable in
-- practice. Any staff member may advance an order; only the owner may cancel.
-- ---------------------------------------------------------------------------
create or replace function public.advance_order_status(
  p_ticket_code text,
  p_status      text
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.orders;
begin
  if not public.is_staff() then
    raise exception 'only staff may change an order status';
  end if;

  if p_status not in ('preparing', 'ready', 'completed', 'cancelled') then
    raise exception 'unknown status %', p_status;
  end if;

  if p_status = 'cancelled' and not public.is_admin() then
    raise exception 'only the owner may cancel an order';
  end if;

  select * into v_order from public.orders
   where ticket_code = upper(trim(p_ticket_code)) for update;

  if v_order.id is null then
    raise exception 'no ticket %', p_ticket_code;
  end if;

  -- Food should not start cooking before it is paid for.
  if p_status in ('preparing', 'ready', 'completed') and v_order.paid_at is null then
    raise exception 'ticket % has not been settled yet', p_ticket_code;
  end if;

  update public.orders
     set status       = p_status,
         completed_at = case when p_status = 'completed' then now() else completed_at end
   where id = v_order.id
   returning * into v_order;

  return v_order;
end;
$$;

grant execute on function public.advance_order_status(text, text) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. Being told when a sold-out dish is back
-- ---------------------------------------------------------------------------
create table public.stock_alerts (
  id          uuid primary key default gen_random_uuid(),
  customer_id uuid not null references auth.users (id) on delete cascade,
  dish_id     text not null references public.dishes (id) on delete cascade,
  created_at  timestamptz not null default now(),
  notified_at timestamptz,

  constraint stock_alerts_one_per_dish unique (customer_id, dish_id)
);

alter table public.stock_alerts enable row level security;

create policy "stock_alerts_own" on public.stock_alerts
  for all
  using (customer_id = auth.uid())
  with check (customer_id = auth.uid());

grant select, insert, delete on public.stock_alerts to authenticated;

-- When a dish comes back, mark every waiting alert so the customer's page can
-- surface it. Deliberately a flag rather than an email: this costs nothing.
create or replace function public.flag_restocked_dishes()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.available and not old.available then
    update public.stock_alerts
       set notified_at = now()
     where dish_id = new.id
       and notified_at is null;
  end if;
  return new;
end;
$$;

create trigger dishes_restocked
  after update of available on public.dishes
  for each row execute function public.flag_restocked_dishes();

-- ---------------------------------------------------------------------------
-- 6. Loyalty stamps
--
-- Counted from completed orders rather than a separate tally, so the number can
-- never drift from what actually happened.
-- ---------------------------------------------------------------------------
create table public.loyalty_rewards (
  id           uuid primary key default gen_random_uuid(),
  customer_id  uuid not null references auth.users (id) on delete cascade,
  code         text not null references public.promo_codes (code) on delete cascade,
  earned_at    timestamptz not null default now(),
  redeemed_at  timestamptz
);

alter table public.loyalty_rewards enable row level security;

create policy "loyalty_own" on public.loyalty_rewards
  for select using (customer_id = auth.uid() or public.is_admin());

grant select on public.loyalty_rewards to authenticated;

/**
 * How many completed orders this customer has, and whether a reward is due.
 * Every fifth completed order earns one.
 */
create or replace function public.my_loyalty()
returns table (completed int, until_next int, rewards jsonb)
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_me    uuid := auth.uid();
  v_count int;
begin
  if v_me is null then
    return query select 0, 5, '[]'::jsonb;
    return;
  end if;

  select count(*)::int into v_count
    from public.orders
   where customer_id = v_me and status = 'completed';

  return query
    select v_count,
           (5 - (v_count % 5))::int,
           coalesce(
             (select jsonb_agg(jsonb_build_object('code', l.code, 'earned_at', l.earned_at, 'redeemed_at', l.redeemed_at))
                from public.loyalty_rewards l where l.customer_id = v_me),
             '[]'::jsonb
           );
end;
$$;

grant execute on function public.my_loyalty() to authenticated;

/**
 * Issues a personal discount code once a customer reaches another multiple of
 * five completed orders. Called by the customer's own orders page; issuing is
 * idempotent because the code is derived from the milestone.
 */
create or replace function public.claim_loyalty_reward()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_me        uuid := auth.uid();
  v_count     int;
  v_milestone int;
  v_earned    int;
  v_code      text;
begin
  if v_me is null then
    raise exception 'sign in to claim a reward';
  end if;

  select count(*)::int into v_count
    from public.orders
   where customer_id = v_me and status = 'completed';

  v_milestone := v_count / 5;
  if v_milestone < 1 then
    raise exception 'you need % more completed orders', 5 - v_count;
  end if;

  select count(*)::int into v_earned
    from public.loyalty_rewards where customer_id = v_me;

  if v_earned >= v_milestone then
    raise exception 'you have already claimed every reward you have earned';
  end if;

  -- Short, personal and unguessable enough for a discount worth 20 pesos.
  v_code := 'SUKI' || upper(substr(replace(v_me::text, '-', ''), 1, 4)) || v_milestone::text;

  insert into public.promo_codes (code, label, kind, value, min_subtotal, usage_limit)
  values (v_code, 'Loyalty reward, 20 pesos off', 'fixed', 20, 60, 1)
  on conflict (code) do nothing;

  insert into public.loyalty_rewards (customer_id, code) values (v_me, v_code);

  return v_code;
end;
$$;

grant execute on function public.claim_loyalty_reward() to authenticated;


-- ============================================================================
-- 20260808000000_recipes.sql
-- ============================================================================
-- ============================================================================
-- Bencris · Recipes, so inventory falls when food is cooked
-- ----------------------------------------------------------------------------
-- Until now the inventory was a list the owner edited by hand, and the menu had
-- no connection to it. Nothing linked "we cooked a pot of sinigang" to "we used
-- up the pork, the kangkong and the gabi", so the stock figures drifted from
-- reality within a day and the low-stock warnings meant nothing.
--
-- WHEN INGREDIENTS ARE DEDUCTED: at cooking time, not at selling time.
--
-- This matters, and getting it the other way round would be wrong. A karinderya
-- cooks a pot in the morning; the pork leaves the inventory at the stove. If
-- ingredients came off per serving sold, the stock would read high all morning
-- and would only ever be correct if every last serving happened to sell.
--
-- So: cook_batch() deducts ingredients and adds servings. Selling a serving
-- only lowers the servings-left count, which the order trigger already does.
-- The two never touch the same number, so nothing is ever counted twice.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. How many servings one batch yields
--
-- Recipe quantities are recorded per BATCH, the way a cook actually thinks:
-- "one pot of sinigang takes one and a half kilos of pork and feeds twenty".
-- ---------------------------------------------------------------------------
alter table public.dishes
  add column batch_yield int not null default 10 check (batch_yield > 0);

comment on column public.dishes.batch_yield is
  'Servings produced by one batch. Recipe quantities below are per batch.';

-- ---------------------------------------------------------------------------
-- 2. The recipe itself
-- ---------------------------------------------------------------------------
create table public.recipe_items (
  dish_id      text not null references public.dishes (id) on delete cascade,
  inventory_id text not null references public.inventory (id) on delete restrict,
  quantity     numeric(10,3) not null check (quantity > 0),

  primary key (dish_id, inventory_id)
);

comment on table public.recipe_items is
  'Ingredients used by ONE BATCH of a dish, in that inventory item''s own unit.';

alter table public.recipe_items enable row level security;

-- Anyone may read a recipe: it is what lets the menu show what is in a dish.
create policy "recipe_items_read_all" on public.recipe_items
  for select using (true);

-- Recipes are a costing decision, so only the owner edits them.
create policy "recipe_items_admin_write" on public.recipe_items
  for all using (public.is_admin()) with check (public.is_admin());

grant select on public.recipe_items to anon, authenticated;
grant insert, update, delete on public.recipe_items to authenticated;

-- ---------------------------------------------------------------------------
-- 3. can_cook() — how many batches the ingredients on hand actually allow
--
-- The limiting ingredient decides. Answers the question the owner asks every
-- morning: "can I still make sinigang today?"
-- ---------------------------------------------------------------------------
create or replace function public.can_cook(p_dish_id text)
returns numeric
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(min(floor(i.stock / r.quantity)), 0)
    from public.recipe_items r
    join public.inventory i on i.id = r.inventory_id
   where r.dish_id = p_dish_id;
$$;

grant execute on function public.can_cook(text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. cook_batch() — the one place ingredients leave the inventory
--
-- Deducts the recipe, adds the servings, and puts the dish back on the menu.
-- Refuses outright if an ingredient would go negative, because a stock figure
-- that can go below zero is worse than no stock figure at all.
-- ---------------------------------------------------------------------------
create or replace function public.cook_batch(
  p_dish_id text,
  p_batches numeric default 1
)
returns public.dishes
language plpgsql
security definer
set search_path = public
as $$
declare
  v_dish    public.dishes;
  v_short   text;
  v_lines   int;
  v_result  public.dishes;
begin
  if not public.is_admin() then
    raise exception 'only the owner may record cooking';
  end if;

  if p_batches is null or p_batches <= 0 then
    raise exception 'how many batches were cooked?';
  end if;

  select * into v_dish from public.dishes where id = p_dish_id;
  if v_dish.id is null then
    raise exception 'no dish %', p_dish_id;
  end if;

  select count(*) into v_lines from public.recipe_items where dish_id = p_dish_id;
  if v_lines = 0 then
    raise exception 'no recipe recorded for %, so ingredients cannot be deducted', v_dish.name;
  end if;

  -- Name the ingredient that is short, rather than failing with a bare error.
  select string_agg(i.name || ' (need ' || round(r.quantity * p_batches, 2) ||
                    ' ' || i.unit || ', have ' || i.stock || ')', ', ')
    into v_short
    from public.recipe_items r
    join public.inventory i on i.id = r.inventory_id
   where r.dish_id = p_dish_id
     and i.stock < r.quantity * p_batches;

  if v_short is not null then
    raise exception 'not enough %', v_short;
  end if;

  update public.inventory i
     set stock = i.stock - (r.quantity * p_batches)
    from public.recipe_items r
   where r.inventory_id = i.id
     and r.dish_id = p_dish_id;

  update public.dishes
     set stock_count = coalesce(stock_count, 0) + (v_dish.batch_yield * p_batches)::int,
         available   = true
   where id = p_dish_id
   returning * into v_result;

  return v_result;
end;
$$;

grant execute on function public.cook_batch(text, numeric) to authenticated;

-- ---------------------------------------------------------------------------
-- 5. Starter ingredients and recipes for the seeded menu
--
-- Quantities are per batch, and are a plausible starting point rather than the
-- owner's real numbers. They exist so the link between cooking and inventory
-- can be demonstrated on day one, and are meant to be corrected in the app.
-- ---------------------------------------------------------------------------
-- The seeded inventory already holds pork, chicken, kangkong, onion, garlic,
-- soy, vinegar, eggs and rice. These are the ones a sinigang recipe needs that
-- were missing.
insert into public.inventory (id, name, unit, stock, reorder_at) values
  ('tomato',   'Kamatis (Tomato)',      'kg',     8,   2),
  ('taro',     'Gabi (Taro)',           'kg',     6,   2),
  ('radish',   'Labanos (Radish)',      'kg',     5,   1.5),
  ('tamarind', 'Sinigang mix',          'sachet', 40,  10),
  ('fishsauce','Patis (Fish sauce)',    'L',      4,   1),
  ('salt',     'Asin (Salt)',           'kg',     5,   1),
  ('pepper',   'Paminta (Pepper)',      'kg',     1.5, 0.4),
  ('laurel',   'Dahon ng Laurel',       'pack',   12,  3),
  ('squash',   'Kalabasa (Squash)',     'kg',     7,   2),
  ('ampalaya', 'Ampalaya (Bitter melon)','kg',    4,   1),
  ('bagoong',  'Bagoong (Shrimp paste)', 'kg',    3,   1)
on conflict (id) do nothing;

-- Pork Sinigang, the example the owner described.
insert into public.recipe_items (dish_id, inventory_id, quantity) values
  ('sinigang', 'pork',      1.5),
  ('sinigang', 'kangkong',  2),
  ('sinigang', 'tomato',    0.5),
  ('sinigang', 'onion',     0.3),
  ('sinigang', 'taro',      0.6),
  ('sinigang', 'radish',    0.4),
  ('sinigang', 'tamarind',  2),
  ('sinigang', 'fishsauce', 0.1),
  ('sinigang', 'salt',      0.05),
  ('sinigang', 'pepper',    0.02)
on conflict do nothing;

insert into public.recipe_items (dish_id, inventory_id, quantity) values
  ('adobo', 'chicken', 2),
  ('adobo', 'soy',     0.4),
  ('adobo', 'vinegar', 0.3),
  ('adobo', 'garlic',  0.2),
  ('adobo', 'pepper',  0.02),
  ('adobo', 'laurel',  1)
on conflict do nothing;

insert into public.recipe_items (dish_id, inventory_id, quantity) values
  ('pinakbet', 'squash',   1.0),
  ('pinakbet', 'ampalaya', 0.6),
  ('pinakbet', 'onion',    0.2),
  ('pinakbet', 'tomato',   0.3),
  ('pinakbet', 'bagoong',  0.2)
on conflict do nothing;

-- Batch sizes for the dishes that now have a recipe.
update public.dishes set batch_yield = 20 where id in ('sinigang', 'adobo');
update public.dishes set batch_yield = 15 where id = 'pinakbet';


-- ============================================================================
-- 20260810000000_business_settings.sql
-- ============================================================================
-- ============================================================================
-- Bencris · The shop's own details, owned by the owner
-- ----------------------------------------------------------------------------
-- The shop name, address, opening hours and contact number were hardcoded in a
-- source file. That meant the single most important information on the site,
-- and the only part a customer needs to actually turn up, could not be changed
-- without a developer. For a client with no technical staff that is a defect,
-- not a detail.
--
-- One row, id = 1, same shape as payment_settings. Anyone may read it because
-- the landing page and the trust pages are public; only the owner may write.
-- ============================================================================

create table public.business_settings (
  id            int primary key default 1 check (id = 1),
  name          text not null default 'Bencris',
  tagline       text not null default 'Kain na, tayo na.',
  blurb         text not null default '',

  address_line  text not null default '',
  district      text not null default '',
  city          text not null default '',
  province      text not null default '',

  phone         text not null default '',
  email         text not null default '',

  -- Opening hours as [{days, opens, closes}], so the owner can have as many
  -- rows as the week actually needs rather than a fixed weekday/weekend pair.
  hours         jsonb not null default '[]'::jsonb,

  updated_at    timestamptz not null default now()
);

alter table public.business_settings enable row level security;

create policy "business_settings_read_all"
  on public.business_settings for select using (true);

create policy "business_settings_admin_write"
  on public.business_settings for all
  using (public.is_admin()) with check (public.is_admin());

grant select on public.business_settings to anon, authenticated;
grant insert, update on public.business_settings to authenticated;

-- Seeded with the placeholders that were previously in the source file, so the
-- owner can see exactly what still needs their real details.
insert into public.business_settings
  (id, name, tagline, blurb, address_line, district, city, province, phone, email, hours)
values (
  1,
  'Bencris',
  'Kain na, tayo na.',
  'Home-cooked Filipino food served fresh every day in Dasmariñas Bayan. Check what is actually cooking before you make the trip.',
  '[Stall number and building]',
  'Dasmariñas Bayan',
  'Dasmariñas',
  'Cavite',
  '[09XX XXX XXXX]',
  '',
  '[{"days":"Monday to Saturday","opens":"6:00 AM","closes":"8:00 PM"},
    {"days":"Sunday","opens":"6:00 AM","closes":"2:00 PM"}]'::jsonb
)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- Staff administration
--
-- promote_to_admin and promote_to_cashier already exist, but there was no way
-- to see who holds what, and no way to take a role away when someone leaves.
-- ---------------------------------------------------------------------------
create or replace function public.list_staff()
returns table (id uuid, email text, full_name text, role text, created_at timestamptz)
language plpgsql
security definer
set search_path = public
stable
as $$
begin
  if not public.is_admin() then
    raise exception 'owners only';
  end if;

  return query
    select p.id, u.email::text, p.full_name, p.role::text, p.created_at
      from public.profiles p
      join auth.users u on u.id = p.id
     where p.role in ('admin', 'cashier')
     order by p.role, u.email;
end;
$$;

grant execute on function public.list_staff() to authenticated;

/**
 * Takes a staff role away without deleting the account, so somebody who leaves
 * simply becomes an ordinary customer and their history stays intact.
 *
 * Refuses to demote the last owner, otherwise the shop could lock itself out
 * of its own dashboard permanently.
 */
create or replace function public.revoke_staff(target_email text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id    uuid;
  v_role  text;
  v_owners int;
begin
  if not public.is_admin() then
    raise exception 'owners only';
  end if;

  select u.id, p.role::text into v_id, v_role
    from auth.users u join public.profiles p on p.id = u.id
   where u.email = target_email;

  if v_id is null then
    raise exception 'no account for %', target_email;
  end if;

  if v_role = 'admin' then
    select count(*) into v_owners from public.profiles where role = 'admin';
    if v_owners <= 1 then
      raise exception 'this is the only owner account, so its access cannot be removed';
    end if;
  end if;

  update public.profiles set role = 'customer' where id = v_id;
end;
$$;

grant execute on function public.revoke_staff(text) to authenticated;

-- ---------------------------------------------------------------------------
-- Review moderation
--
-- The delete policy already allowed the owner to remove a review; there was no
-- way to read them all in one place to decide.
-- ---------------------------------------------------------------------------
create or replace function public.all_reviews()
returns table (
  id uuid, dish_id text, dish_name text, ticket_code text,
  rating int, comment text, created_at timestamptz
)
language plpgsql
security definer
set search_path = public
stable
as $$
begin
  if not public.is_admin() then
    raise exception 'owners only';
  end if;

  return query
    select r.id, r.dish_id, d.name, r.ticket_code, r.rating, r.comment, r.created_at
      from public.reviews r
      join public.dishes d on d.id = r.dish_id
     order by r.created_at desc;
end;
$$;

grant execute on function public.all_reviews() to authenticated;


-- ============================================================================
-- 20260811000000_more_recipes.sql
-- ============================================================================
-- ============================================================================
-- Bencris · Recipes for the rest of the menu
-- ----------------------------------------------------------------------------
-- Three dishes had a recipe and six did not, which meant the low-stock warnings
-- only told half the story and most of the menu could be cooked without the
-- inventory noticing.
--
-- Quantities are per batch, in each ingredient's own unit, and are a plausible
-- starting point rather than the owner's real numbers. They are meant to be
-- corrected on the Menu screen once the kitchen weighs a real pot.
-- ============================================================================

insert into public.inventory (id, name, unit, stock, reorder_at) values
  ('beef',      'Baka (Beef)',            'kg',   6,   2),
  ('sugar',     'Asukal (Sugar)',         'kg',   8,   2),
  ('wrapper',   'Lumpia wrapper',         'pack', 15,  4),
  ('carrot',    'Karot (Carrot)',         'kg',   5,   1.5),
  ('potato',    'Patatas (Potato)',       'kg',   7,   2),
  ('liver',     'Liver spread',           'can',  10,  3),
  ('tomato-sauce','Tomato sauce',         'can',  12,  3),
  ('bellpepper','Bell pepper',            'kg',   3,   1),
  ('milk',      'Gatas (Evaporated milk)','can',  20,  5),
  ('ice',       'Yelo (Ice)',             'kg',   30,  8),
  ('beans',     'Halo-halo beans mix',    'kg',   5,   1.5),
  ('ube',       'Ube halaya',             'kg',   3,   1),
  ('sago-pearl','Sago pearls',            'kg',   4,   1),
  ('gulaman',   'Gulaman bars',           'pack', 12,  3),
  ('cooking-oil','Mantika (Cooking oil)', 'L',    8,   2)
on conflict (id) do nothing;

-- Tapsilog: cured beef, garlic rice, fried egg.
insert into public.recipe_items (dish_id, inventory_id, quantity) values
  ('tapsilog', 'beef',        2),
  ('tapsilog', 'rice',        3),
  ('tapsilog', 'eggs',        1),
  ('tapsilog', 'garlic',      0.15),
  ('tapsilog', 'soy',         0.2),
  ('tapsilog', 'vinegar',     0.1),
  ('tapsilog', 'sugar',       0.15),
  ('tapsilog', 'cooking-oil', 0.3)
on conflict do nothing;

-- Tocilog: sweet cured pork, garlic rice, fried egg.
insert into public.recipe_items (dish_id, inventory_id, quantity) values
  ('tocilog', 'pork',        2),
  ('tocilog', 'rice',        3),
  ('tocilog', 'eggs',        1),
  ('tocilog', 'sugar',       0.4),
  ('tocilog', 'garlic',      0.15),
  ('tocilog', 'cooking-oil', 0.3)
on conflict do nothing;

-- Lumpiang Shanghai: ground pork rolls, fried.
insert into public.recipe_items (dish_id, inventory_id, quantity) values
  ('lumpia', 'pork',        1.5),
  ('lumpia', 'wrapper',     2),
  ('lumpia', 'carrot',      0.4),
  ('lumpia', 'onion',       0.2),
  ('lumpia', 'garlic',      0.1),
  ('lumpia', 'eggs',        0.5),
  ('lumpia', 'cooking-oil', 0.6),
  ('lumpia', 'salt',        0.03),
  ('lumpia', 'pepper',      0.02)
on conflict do nothing;

-- Kalderetang Kambing: goat in tomato and liver sauce.
insert into public.recipe_items (dish_id, inventory_id, quantity) values
  ('kaldereta', 'goat',         2),
  ('kaldereta', 'tomato-sauce', 2),
  ('kaldereta', 'liver',        1),
  ('kaldereta', 'potato',       0.8),
  ('kaldereta', 'carrot',       0.5),
  ('kaldereta', 'bellpepper',   0.3),
  ('kaldereta', 'onion',        0.3),
  ('kaldereta', 'garlic',       0.15),
  ('kaldereta', 'laurel',       1)
on conflict do nothing;

-- Halo-Halo: shaved ice, milk, sweet beans, ube.
insert into public.recipe_items (dish_id, inventory_id, quantity) values
  ('halohalo', 'ice',    4),
  ('halohalo', 'milk',   4),
  ('halohalo', 'beans',  1),
  ('halohalo', 'ube',    0.5),
  ('halohalo', 'sugar',  0.5),
  ('halohalo', 'gulaman', 1)
on conflict do nothing;

-- Sago't Gulaman: pearls, jelly, brown sugar syrup.
insert into public.recipe_items (dish_id, inventory_id, quantity) values
  ('sago', 'sago-pearl', 0.8),
  ('sago', 'gulaman',    2),
  ('sago', 'sugar',      1),
  ('sago', 'ice',        3)
on conflict do nothing;

-- Batch sizes. Drinks and merienda come out of a larger pot than an ulam.
update public.dishes set batch_yield = 20 where id in ('tapsilog', 'tocilog');
update public.dishes set batch_yield = 30 where id in ('lumpia', 'sago', 'halohalo');
update public.dishes set batch_yield = 15 where id = 'kaldereta';


-- ============================================================================
-- 20260812000000_create_staff.sql
-- ============================================================================
-- ============================================================================
-- Bencris · The owner creates staff logins directly
-- ----------------------------------------------------------------------------
-- Granting a role only worked if the person had already signed up on the
-- customer page, which is the wrong way round for a karinderya. The owner hires
-- a cashier and hands them a login; the cashier does not register themselves
-- and then wait to be approved.
--
-- SECURITY. This writes into auth.users, which is normally reachable only with
-- the service-role key. That key must never reach a browser, so instead the
-- work happens inside a SECURITY DEFINER function that checks is_admin() first.
-- The privilege belongs to the function, not to the caller: an ordinary
-- customer calling this gets refused, and no secret is shipped to the client.
--
-- The column list mirrors supabase/seed.sql, including the empty-string token
-- fields. GoTrue scans those into Go strings and a NULL breaks sign-in with a
-- misleading "Database error querying schema".
-- ============================================================================

create or replace function public.create_staff_account(
  p_email     text,
  p_password  text,
  p_full_name text,
  p_role      text
)
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_email text := lower(trim(p_email));
  v_id    uuid := gen_random_uuid();
begin
  if not public.is_admin() then
    raise exception 'only the owner may create staff logins';
  end if;

  if p_role not in ('admin', 'cashier') then
    raise exception 'role must be admin or cashier';
  end if;

  if v_email is null or v_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'that does not look like an email address';
  end if;

  if p_password is null or length(p_password) < 6 then
    raise exception 'the password needs at least 6 characters';
  end if;

  -- Already registered? Just grant the role rather than failing, which is what
  -- the owner meant anyway.
  if exists (select 1 from auth.users where email = v_email) then
    update public.profiles p
       set role = p_role::public.user_role,
           full_name = coalesce(nullif(trim(p_full_name), ''), p.full_name)
      from auth.users u
     where u.email = v_email and p.id = u.id;
    return 'existing account granted ' || p_role || ' access';
  end if;

  insert into auth.users (
    instance_id, id, aud, role, email, encrypted_password,
    email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
    created_at, updated_at,
    confirmation_token, recovery_token, email_change,
    email_change_token_new, email_change_token_current,
    phone_change, phone_change_token, reauthentication_token
  ) values (
    '00000000-0000-0000-0000-000000000000',
    v_id, 'authenticated', 'authenticated',
    v_email,
    extensions.crypt(p_password, extensions.gen_salt('bf')),
    now(),                                   -- confirmed, so they can sign in at once
    '{"provider":"email","providers":["email"]}',
    jsonb_build_object('full_name', trim(coalesce(p_full_name, ''))),
    now(), now(),
    '', '', '', '', '', '', '', ''
  );

  insert into auth.identities (
    id, user_id, provider_id, identity_data, provider,
    last_sign_in_at, created_at, updated_at
  ) values (
    gen_random_uuid(), v_id, v_id::text,
    jsonb_build_object('sub', v_id::text, 'email', v_email),
    'email', now(), now(), now()
  );

  -- The signup trigger has already made a 'customer' profile. Assign the role
  -- the owner actually chose.
  update public.profiles
     set role = p_role::public.user_role,
         full_name = nullif(trim(coalesce(p_full_name, '')), '')
   where id = v_id;

  return 'created';
end;
$$;

grant execute on function public.create_staff_account(text, text, text, text) to authenticated;

/**
 * Resets a staff password, for the day somebody forgets theirs.
 */
create or replace function public.set_staff_password(
  p_email    text,
  p_password text
)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if not public.is_admin() then
    raise exception 'only the owner may change a staff password';
  end if;

  if p_password is null or length(p_password) < 6 then
    raise exception 'the password needs at least 6 characters';
  end if;

  update auth.users
     set encrypted_password = extensions.crypt(p_password, extensions.gen_salt('bf')),
         updated_at = now()
   where email = lower(trim(p_email))
     and id in (select id from public.profiles where role in ('admin', 'cashier'));

  if not found then
    raise exception 'no staff account for %', p_email;
  end if;
end;
$$;

grant execute on function public.set_staff_password(text, text) to authenticated;


-- ============================================================================
-- 20260813000000_inventory_par_levels.sql
-- ============================================================================
-- ============================================================================
-- Bencris · Inventory that answers "how much do I still need to buy?"
-- ----------------------------------------------------------------------------
-- The old model had "reorder at": a bare threshold with no context. Seeing
-- "2.5" next to "reorder at 1" tells the owner almost nothing, because it never
-- says how much they are supposed to have in the first place.
--
-- What the owner actually wants to say is "a full stock of this is 100 eggs".
-- Then the count means something: 30 of 100, so buy 70. That shortfall is
-- exactly the number to write on the palengke list.
--
-- last_delivery also had to be typed by hand, so it was wrong the moment anyone
-- forgot. Receiving stock now stamps it automatically.
-- ============================================================================

alter table public.inventory
  add column par_level numeric(10,2) not null default 0 check (par_level >= 0);

comment on column public.inventory.par_level is
  'A full stock of this ingredient. The screen shows stock out of par_level, and par_level minus stock is what to buy.';

-- last_delivery was free text ('Apr 22', or the em dash placeholder). A real
-- date lets the screen say "3 days ago" and lets it be set automatically.
alter table public.inventory
  add column last_received_at timestamptz;

comment on column public.inventory.last_received_at is
  'Stamped automatically by receive_stock(). The old free-text last_delivery is kept for anything already recorded.';

-- Seed a sensible full-stock figure from what is already there, so no row
-- starts at zero and the screen is useful immediately. The owner corrects
-- these on the Inventory screen.
update public.inventory
   set par_level = greatest(round(reorder_at * 4, 2), round(stock, 2), 1);

-- ---------------------------------------------------------------------------
-- receive_stock() — the one way stock goes UP.
--
-- Cooking takes ingredients out (cook_batch); buying puts them back. Keeping
-- both as explicit actions means the stock figure always has an explanation,
-- and the delivery date can never drift out of step with reality.
-- ---------------------------------------------------------------------------
create or replace function public.receive_stock(
  p_inventory_id text,
  p_quantity     numeric
)
returns public.inventory
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item public.inventory;
begin
  if not public.is_admin() then
    raise exception 'only the owner may record a delivery';
  end if;

  if p_quantity is null or p_quantity <= 0 then
    raise exception 'how much was delivered?';
  end if;

  update public.inventory
     set stock            = stock + p_quantity,
         last_received_at = now(),
         last_delivery    = to_char(now(), 'Mon DD')
   where id = p_inventory_id
   returning * into v_item;

  if v_item.id is null then
    raise exception 'no ingredient %', p_inventory_id;
  end if;

  return v_item;
end;
$$;

grant execute on function public.receive_stock(text, numeric) to authenticated;

-- ---------------------------------------------------------------------------
-- shopping_list() — what to buy, and how much.
--
-- Everything sitting below its par level, with the exact shortfall. This is the
-- list the owner takes to the palengke.
-- ---------------------------------------------------------------------------
create or replace function public.shopping_list()
returns table (
  id text, name text, unit text,
  stock numeric, par_level numeric, shortfall numeric,
  last_received_at timestamptz
)
language sql
security definer
set search_path = public
stable
as $$
  select i.id, i.name, i.unit,
         i.stock, i.par_level,
         round(i.par_level - i.stock, 2) as shortfall,
         i.last_received_at
    from public.inventory i
   where i.par_level > 0
     and i.stock < i.par_level
   order by (i.stock / nullif(i.par_level, 0)) asc;
$$;

grant execute on function public.shopping_list() to authenticated;


-- ---------------------------------------------------------------------------
-- Tell the CLI these are applied, so a future `supabase db push` skips them.
-- ---------------------------------------------------------------------------
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (version text primary key);

insert into supabase_migrations.schema_migrations (version) values
  ('20260805000000'),
  ('20260806000000'),
  ('20260807000000'),
  ('20260808000000'),
  ('20260810000000'),
  ('20260811000000'),
  ('20260812000000'),
  ('20260813000000')
on conflict (version) do nothing;

commit;
